duts {
  id: "xrd"
  vendor: CISCO
  hardware_model: "xrd"
  ports {
    id: "port1"
  }
}
ates {
  id: "otg"
  vendor: IXIA
  ports {
    id: "port1"
  }
}
links {
  a: "otg:port1"
  b: "xrd:port1"
}