duts {
  id: "xrd"
  vendor: CISCO
  hardware_model: "xrd"
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
duts {
  id: "e8000"
  vendor: CISCO
  hardware_model: "8201"
  ports {
    id: "port1"
  }
}
ates {
  id: "otg"
  vendor: IXIA
  ports {
    id: "port1"
  }
}
links {
  a: "otg:port1"
  b: "xrd:port1"
}