name: "vendors"
nodes: {
  name: "xrd"
  vendor: CISCO
  model: "xrd"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/cisco/xrd:ga"
    file: "cisco.cfg"
  }
  interfaces: {
    key: "eth1"
    value: {
      name: "GigabitEthernet0/0/0/0"
    }
  }
}
nodes: {
  name: "otg"
  vendor: KEYSIGHT
  version: "0.0.1-9999"
}
# Links from otg
links: {
  a_node: "otg"
  a_int: "eth1"
  z_node: "xrd"
  z_int: "eth1"
}